name: build

on: push

jobs:
  build:
    name: build-examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Install libraries
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: MajicDesigns/MD_UISwitch
          tag: 2.1.0
          path: libraries
      - name: Compile examples using Arduino Uno
        uses: pfeerick/arduino-builder-action@master
        with:
          board: "arduino:avr:uno"
