name: build

on: push

jobs:
  build:
    name: build-examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Test compile for Arduino
        uses: ArminJo/arduino-test-compile@v2
        with:
          sketches-exclude: MD_MAX72XX_Message_ESP8266
          required-libraries: SPI,MD_UISwitch,SdFat

